stages:
  - validation

before_script:
  - apt-get -y update
  - apt-get -y install git sudo wget lsb-release
  - .gitlab/install_pdk.sh

Validation:
  stage: validation
  image: ubuntu:18.04
  before_script:
    - .gitlab/install_pdk.sh
  script:
    - '.gitlab/test_script.sh'
